### ISSUE TITLE
怎么将两个节点之间的连线默认为poliline呢？

### ISSUE THREAD

**Issue by phoebemoon16** [jnoodle/vue-flowchart-editor#17]
怎么将两个节点之间的连线默认为poliline呢？因为默认的是smooth，我们项目需要默认为poliline。

**Comment by 364988343** [comment]
你搞好了吗？

**Comment by 364988343** [comment]
graphConfig -->    edgeDefaultShape: 'flow-polyline-round',

**Comment by phoebemoon16** [comment]
thank you so muck ><
